### ISSUE TITLE
Php warning only with mysql driver

### ISSUE THREAD

**Issue by jimi75** [xiaohutai/jsonapi#28]
When the app is configured with mysql driver i get a warning in the api response calling  a collection of entities (json/{contenttypeslug}) before the dta

`Warning:  Invalid argument supplied for foreach() in /path/to/folder/vendor/bolt/bolt/src/Storage/Mapping/MetadataDriver.php on line 238

<img width="690" alt="screen shot 2016-09-20 at 02 11 42" src="https://cloud.githubusercontent.com/assets/1430380/18653072/a5b41278-7ed7-11e6-9269-1bb1cb7fed29.png">

**Comment by Raistlfiren** [comment]
@jimi75 What version of PHP are you running? I can't seem to duplicate the issue with PHP 5.6 and mysqlnd 5.0.11 module. It seems like that has to do with the `MetadataDriver.php` that is being handled by Bolt and not the extension. What does your content type look like as well? 

Thanks!

**Comment by bobdenotter** [comment]
Also, which version of Bolt?

**Comment by jimi75** [comment]
php 7.0.11
mysql 5.5.52
bolt 3.1.0
bolt/jsonapi 3.0.3

Strange bug. Its only occurs when the content type definition has '_' or '-' (underscore or slash) and use a repeater. 

@Raistlfiren you are right is related to bolt. Some kind of bad behavior with repeater fields. 

I will close this one, try to figured the exactly problem and open a new issue in bolt.

pd: Guys you are doing a great job! Bolt is amazing, thanks for all the hard work.

**Comment by bobdenotter** [comment]
@jimi75 Ah, the dreaded underscore.. See https://github.com/bolt/bolt/pull/5787.
