### ISSUE TITLE
Not Normalize ContentTypes in Actions

### ISSUE THREAD

**Issue by imonly** [xiaohutai/jsonapi#33]
Please add normalize to contenttype in actions

Url "/en-works/1" work correct
Url "/json/en-works/1" have trouble ;(

An exception occurred while executing 'SELECT ru-works.\* FROM bolt_en_works en-works WHERE en-works.id = ? ORDER BY id ASC LIMIT 1 OFFSET 0' with params ["1"]: SQLSTATE[HY000]: General error: 1 near "*": syntax error

**Comment by Raistlfiren** [comment]
@imonly Is `en-works` supposed to be a content type?

**Comment by imonly** [comment]
i have content type with this name: https://docs.bolt.cm/3.0/howto/building-multilingual-websites

**Comment by xiaohutai** [comment]
It's been a while, so I'm closing this issue.

I'd suggest using https://github.com/BoltTranslate/Translate instead.
Furthermore, you can access multilingual content via the JSON API, by adding a `_locale` to your query params.
