### ISSUE TITLE
[RFC] Bolt Translate Compatibility

### ISSUE THREAD

**Issue by zomars** [xiaohutai/jsonapi#38]
It would be nice to have this extension working with the [bolt-translate](https://github.com/AnimalDesign/bolt-translate) extension.

**Comment by xiaohutai** [comment]
A bit late to the party, but it seems there's no problem at all with [Translate](https://github.com/BoltTranslate/Translate), the only thing you need to do is to add a `&_locale=en` to your call and Bolt + Translate handles the rest.

**Comment by xiaohutai** [comment]
Added this info to readme, so closing this one.

**Comment by zomars** [comment]
Thank you!
