### ISSUE TITLE
RootAction not found

### ISSUE THREAD

**Issue by xiaohutai** [xiaohutai/jsonapi#49]
Hi @Raistlfiren 

See https://github.com/xiaohutai/jsonapi/commit/227ea53c09b34c755802f51474cfd85e8a72630a#diff-9cc95dc86372929e38743cf6f5e52f35

The namespace says:
```
namespace Bolt\Extension\Bolt\JsonApi\Action;
```

but the file is located in
```
src/Controllers/RootAction.php
```

**Comment by Raistlfiren** [comment]
Thanks @xiaohutai! I missed that. :( I appreciate the issue. I am updating with a new release v3.0.12

**Comment by xiaohutai** [comment]
@Raistlfiren, thank you! I really appreciate your time and effort 👍

**Comment by Raistlfiren** [comment]
No problem @xiaohutai :)
