### ISSUE TITLE
Get contenttype with a relationship to itself.

### ISSUE THREAD

**Issue by julioinzunza** [xiaohutai/jsonapi#51]
I have a contenttype related with itself to select related entries by my own. The problem is that jsonapi send an 500 error in my ajax request.

Do you know what problem is?

**Comment by Raistlfiren** [comment]
@julioinzunza -

Can you please give me more details like what the contentype is like(YAML information) and what version of Bolt and the extension you are running?

Thanks!

**Comment by Raistlfiren** [comment]
@julioinzunza - ping! Any further updates on this issue? Otherwise, I am closing it.

**Comment by xiaohutai** [comment]
There's a bug in Bolt with the `app['query']` class. I've noticed this issue with some other extensions as well.

Basically, if you do this:

```
pages:
    (...)
    relations:
        pages:
            (...)
```
You'll get a `QueryException`.

See https://github.com/bolt/bolt/issues/6691

**Comment by xiaohutai** [comment]
Fixed via https://github.com/bolt/bolt/issues/6779
