### ISSUE TITLE
Uncaught Exception: InvalidArgumentException

### ISSUE THREAD

**Issue by joaoeduardo** [xiaohutai/jsonapi#58]
Package version: 3.0.13
Bolt version: 3.2.14

> InvalidArgumentException in ControllerResolver.php line 173: 
Unable to find controller "listContent".

**Comment by bobdenotter** [comment]
This is being worked on. A new version will be out soon.

**Comment by joaoeduardo** [comment]
Thanks. I will wait.

**Comment by joaoeduardo** [comment]
Do you have a deadline for this? Thanks.

**Comment by bobdenotter** [comment]
A PR is in the queue #59

**Comment by xiaohutai** [comment]
Hey @joaoeduardo ,

Please check the latest version of the jsonapi extension: `v3.0.15` (or otherwise `v3.0.14`) and see if that works. I'm closing this issue for now.

Feel free to open a new issue if the new version has issues. Thanks
