### ISSUE TITLE
Processing values before response

### ISSUE THREAD

**Issue by tameroski** [xiaohutai/jsonapi#63]
I have password fields on a content type, stored as plain text (as Bob recommended [here](https://github.com/bolt/bolt/issues/3314)), and i'd like to expose them encoded in the JSON response. Any idea on how i can achieve that, pls ?

**Comment by tameroski** [comment]
Maybe exposing encoded passwords is not a very good idea ... Would be better to be able to make a filtered query with the encoded password as parameter and see if it matches entries. But the problem is almost the same: how can i hook onto the plugin's filter matching feature, so i can do a password verification ?

**Comment by xiaohutai** [comment]
I would not do password authentication with this extension. I would not even expose passwords (hashed or not) at all. You can hide fields, by defining which fields are allowed in the config file.

Authentication would be something on a different layer.
You'll probably need to something custom that is outside the scope of this extension.

**Comment by xiaohutai** [comment]
The [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) may help in extending existing services.

I'm closing this issue as part of clean up. Feel free to re-open the issue or open a new issue.
