### ISSUE TITLE
`included` should always be an array

### ISSUE THREAD

**Issue by rwd** [xiaohutai/jsonapi#66]
Per the [JSON API spec](http://jsonapi.org/format/#document-top-level), `included` should always be an array, but in the output of this extension (observed at version 3.0.15), it is _sometimes_ a JSON object keyed with string representations of integers, e.g. `"0"`, `"1"`, `"2"`.

This prevents consumption by clients.

**Comment by xiaohutai** [comment]
Hi @rwd Thanks for reporting this issue.
Could you check if `dev-master` in Bolt works for you, then I'll make a new release.

https://github.com/xiaohutai/jsonapi/commit/43ede96075560c14345dee3b437dd2837d6a048f

**Comment by xiaohutai** [comment]
I went ahead and made a release [v3.0.16](https://github.com/xiaohutai/jsonapi/releases/tag/v3.0.16).

If you are still experiencing issues, let me know.

**Comment by rwd** [comment]
@xiaohutai the new release has resolved this issue for us, thank you.
