### ISSUE TITLE
paging error

### ISSUE THREAD

**Issue by severak** [xiaohutai/jsonapi#67]
there seems to be an error with paging. For my site, it returns paging links like this:

```
"links": {
        "self": "http:\/\/tee.svita.cz\/jsonapi\/trip?\/tee\/jsonapi\/trip=",
        "last": "http:\/\/tee.svita.cz\/jsonapi\/trip?\/tee\/jsonapi\/trip=&page[number]=8",
        "next": "http:\/\/tee.svita.cz\/jsonapi\/trip?\/tee\/jsonapi\/trip=&page[number]=2"
    },
```

Note the `=&` instead of `?` above.

**Comment by xiaohutai** [comment]
Hi,
What version of Bolt is this?

The first query param is a bit weird:

* `/tee/jsonapi/trip` =
* `page[number]` = `8`

Not sure if it's Bolt doing this or something else.

**Comment by severak** [comment]
it's Bolt 3.3.3

**Comment by xiaohutai** [comment]
Do you know if it worked before (Bolt 3.2) and that it is now broken in Bolt 3.3?
I've seen some new stuff going on in Bolt 3.3 which may have broken this.

**Comment by GwendolenLynch** [comment]
> Note the `=&` instead of `?` above.

Just to add to this, the use of the `&` delimiter is correct `@see` https://tools.ietf.org/html/rfc3986#section-3.3 … the URIs do not look correct, however.

**Comment by severak** [comment]
> Do you know if it worked before (Bolt 3.2) and that it is now broken in Bolt 3.3?

not tested it in Bolt 3.2

**Comment by xiaohutai** [comment]
Hmm, something weird is going on, because if I navigate to http://tee.svita.cz/jsonapi/ (with trailing `/`), it redirected to http://tee.svita.cz/jsonapi?/tee/jsonapi/.

I don't know why that is (maybe a rewrite rule or something).

**Comment by xiaohutai** [comment]
I'm cleaning up some issues. Feel free to re-open or open a new issue.
