### ISSUE TITLE
Additional Queries thows error

### ISSUE THREAD

**Issue by rainpoiss** [xiaohutai/jsonapi#69]
In readme there is some querys:

/{ct}/search?q={query} | Searches for {query} in a specific contenttype.
and
/search?q={query} | Searches for {query} in all contenttypes.

when using them i get an error: 

Uncaught Exception: ContextErrorException .

ContextErrorException in ParameterFactory.php line 29: 
Notice: Undefined index: contentType

**Comment by xiaohutai** [comment]
I can't seem to find why this goes wrong since the code has been refactored.
It seems that this must've been broken for quite some time too 🤔

**Comment by xiaohutai** [comment]
Just made a release. Fixed in v3.0.18
