### ISSUE TITLE
Filter with AND clause or BETWEEN variant for date fields

### ISSUE THREAD

**Issue by Raxta** [xiaohutai/jsonapi#72]
In filter parameter options combine with OR operator. Anybody know's how pass options to filter parameter that they combine in query with AND clause? Or maybe for data field exist another method for filterring with BETWEEN clause?

**Comment by xiaohutai** [comment]
This one's a bit tricky, but there's a hackish workaround that still works; do it like so:

```
&filter[datepublish]=>2017-01-01%20%26%26%20<2017-06-01
```

So the value is basically:

```
>2017-01-01 && <2018-01-01
```

**Comment by xiaohutai** [comment]
See also: https://github.com/json-api/json-api/issues/372
