### ISSUE TITLE
Content types containing repeaters throw an error if the repeater is populated.

### ISSUE THREAD

**Issue by araglin** [xiaohutai/jsonapi#77]
When a contenttype has a repeater in it, and there is at least one entry in one set of the repeater, an error is produced.

![image](https://user-images.githubusercontent.com/2364929/38151702-f30846f8-3429-11e8-8ed0-176feef2a4b9.png)

If there's no repeater content at all, the element can be present, but no error occurs:

![image](https://user-images.githubusercontent.com/2364929/38151728-0d040b50-342a-11e8-8de6-e71ff51042ac.png)

**Comment by Raistlfiren** [comment]
@araglin I am unable to replicate this issue. Can you please post the contenttypes.yml file that you used to produce this issue?

**Comment by araglin** [comment]
It's just the default contenttypes.yml with one added type: geographies. I've been trying to use repeaters with the showcase type, just to test them with the API.

[contenttypes.yml.zip](https://github.com/xiaohutai/jsonapi/files/1886684/contenttypes.yml.zip)

**Comment by Raistlfiren** [comment]
What version of Bolt are you running? I am now wondering if your Bolt version is older and doesn't support getBlock().

**Comment by xiaohutai** [comment]
Closing this issue as part of clean up. If it still occurs, update Bolt and JSONAPI and see if that helps. Otherwise, feel free to open a new issue with steps for reproduction.
