### ISSUE TITLE
Call to a member function format() on a non-object

### ISSUE THREAD

**Issue by AdriaanTV** [xiaohutai/jsonapi#8]
If you use a field with a date type in your <code>contenttypes.yml</code>, and I access the data through <code>/json/{ct}</code> it throws an error:

**There is a fatal error in the 'bolt/jsonapi' extension loaded on your Bolt Installation.
Error: Call to a member function format() on a non-object
File: extensions/vendor/bolt/jsonapi/Extension.php
Line: 992**

Possible trouble: in <code>jsonapi.bolt.yml</code> there's value <code>date-iso-8601: true</code>, if I set it to false, the error disappears.

**Comment by Raistlfiren** [comment]
This should be fixed in the latest update with V3. I am closing this issue, please reopen this if it is still a problem.
