### ISSUE TITLE
Owner name in posts fields

### ISSUE THREAD

**Issue by HorlogeSkynet** [xiaohutai/jsonapi#84]
Hey over here !

We started (again) working with your API, but one question remains for us : How could we retrieve the owner name of a post easily (`users.displayname` within the Bolt Schema) ?
`attributes` object already contains a `ownerid` field but it's a kinda pretty limited piece of information...

Thanks, bye :wave:

**Comment by xiaohutai** [comment]
I've made a solution in a PR. But I'm not sure if this is the nicest approach. The PR #85 adds a `ownerdisplayname` if you set `enabledisplaynames` to `true` in your config file.

**Comment by HorlogeSkynet** [comment]
Hey ! Thanks for this. I fear we are not enough "used to" Bolt and Plugins environment to share your concerns, but as long as "it just works" we'd be totally OK :smiley: 

Closing here as #85 is opened.

**Comment by xiaohutai** [comment]
I'll hope to have it merged next week or so 👍

**Comment by HorlogeSkynet** [comment]
Perfect, that's pretty cool actually.
Could we expect to have a thought before from Bob or Gawain maybe ? :thinking:
